### ISSUE TITLE
"Assets to Upload" parameter as optional instead of required

### ISSUE THREAD

**Issue by jdshkolnik** [jakobehn/VSTSGitHubTasks#11]
Shouldn't it be optional? Neither GitHub nor Octokit require assets when creating a release.

**Comment by jakobehn** [comment]
Makes sense,  I haven't had this case yet but I can definitely see the need for this. I'll change this parameter to optional

**Comment by jdshkolnik** [comment]
Thank you. I really appreciate you finding time for all this.

**Comment by jakobehn** [comment]
I just uploaded a new version (0.10.1) that changes the Assets to Upload parameter to be optional

**Comment by jdshkolnik** [comment]
Closing this issue since it worked after 0.10.1. Can troubleshoot new error in #15.
