### ISSUE TITLE
'Assets to upload' prepends fallback if path starts with a variable.

### ISSUE THREAD

**Issue by b0wter** [jakobehn/VSTSGitHubTasks#24]
If i am using the following path:
```
D:\a\r1\a\Binaries_SharpStrap_Linux_Generic_x64\drop_linux_generic_x64\src.zip
```
as contents for the 'Assets to upload' property my release definition works flawlessly. I want to replace the hardcoded path with strings and wanted to start replaceing ```D:\a\r1\a``` with ```$(AGENT_RELEASEDIRECTORY)```. However, when doing so the resulting path is:
```
D:\a\_tasks\PublishGitHubRelease_52a55b38-da88-4272-9cb5-8627a5197311\0.11.2\$(AGENT_RELEASEDIRECTORY)\Binaries_SharpStrap_Linux_Generic_x64\drop_linux_generic_x64
```
I have no idea where the ```D:\a\_tasks\PublishGitHubRelease_52a55b38-da88-4272-9cb5-8627a5197311\0.11.2\``` is coming from. :(

**Comment by jakobehn** [comment]
The variable name is not correct. Try $(Agent.ReleaseDirectory) instead

**Comment by b0wter** [comment]
Oh, I am sorry. Still learning the ropes. I was blindly copying the variable from the ```Job Init```-step.
