### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by andreujuanc** [jakobehn/VSTSGitHubTasks#5]
Hello, 

I wanted to integrate this project into my workflow, but it seems a bit outdated. There are 3 pull requests with no replies. 
Is the autor still working on this?

Looking forward to this one.

Thanks!

**Comment by jdshkolnik** [comment]
I suspect it might be dead. I can't get it to work...although that might be particular to me.

**Comment by jakobehn** [comment]
I've merged a few of the pull requests, and published a new version to the market place.  Thanks for using the task!

**Comment by jdshkolnik** [comment]
@jakobehn Thanks but unable to update from previous version. I opened a separate issue for it.

**Comment by jakobehn** [comment]
Just uploaded a new version, can you try again? Thanks

**Comment by jdshkolnik** [comment]
It updated, thanks.
